In [15]:
import cv2
import numpy as np
import time

img_path = '/Users/Alex/Documents/GitHub/1st-DL-CVMarathon/homework/img/lena.png'
img = cv2.imread(img_path, cv2.IMREAD_COLOR)

#取得圖片的資訊，即print(img.shape)可看到的列跟欄 [:2]表示集合中的第1和2個元素0、1、2，包頭不包尾

rows, cols = img.shape[:2]

# 取得旋轉矩陣 (中心點、旋轉角度、縮放程度)
# getRotationMatrix2D(center, angle, scale)

M_rotate = cv2.getRotationMatrix2D((rows//2, cols//2), 45, 0.5)
print('Rotation Matrix')
print(M_rotate)
print()

#取得平移矩陣
M_translate= np.array([[1,0,100],[0,1,-50]],dtype=np.float32)
print('Translation Matrix')
print(M_translate)
print()

#旋轉 cv2.warpAffine 圖片、變換矩陣、變換後的圖片大小
img_rotate=cv2.warpAffine(img, M_rotate, (rows, cols))

#平移
img_rotate_trans = cv2.warpAffine(img_rotate, M_translate, (rows, cols))

# 組合 + 顯示圖片
img_show_rotate_trans = np.hstack((img, img_rotate, img_rotate_trans))
cv2.imshow('Rotate 45, scale 0.5, Translate x+100, y-50', img_show_rotate_trans)
cv2.waitKey(0)
cv2.destroyAllWindows()



Rotation Matrix
[[  0.35355339   0.35355339  74.98066402]
 [ -0.35355339   0.35355339 256.        ]]

Translation Matrix
[[  1.   0. 100.]
 [  0.   1. -50.]]



In [19]:
#方法二 

import cv2
import numpy as np
import time

img_path = '/Users/Alex/Documents/GitHub/1st-DL-CVMarathon/homework/img/lena.png'
img = cv2.imread(img_path, cv2.IMREAD_COLOR)

# 給定兩兩一對，共三對的點
# 這邊我們先用手動設定三對點，一般情況下會有點的資料或是透過介面手動標記三個點

rows, cols = img.shape[:2]
pt1 = np.array([[50,50],[300,100],[200,300]], dtype = np.float32)
pt2 = np.array([[80,80],[330,150],[300,300]], dtype = np.float32)

# 取得 affine 矩陣並做 affine 操作

M_affine = cv2.warpAffine(img, pt1, (rows, cols))



error: OpenCV(4.1.2) C:\projects\opencv-python\opencv\modules\imgproc\src\imgwarp.cpp:2603: error: (-215:Assertion failed) (M0.type() == CV_32F || M0.type() == CV_64F) && M0.rows == 2 && M0.cols == 3 in function 'cv::warpAffine'
